import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "./components/Footer";
import Navbar from "./components/Navbar";
import Header from "./components/Header";
import { CartProvider } from './context/CartContext';
import Products from './allProducts/page';
import Features from "./components/features";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CartProvider>
          {/* <Products /> */}
          {/* <Features /> */}
            {/* <Header /> */}
            {/* <Navbar /> */}
            {children}
            {/* <Footer /> */}
        </CartProvider>
      </body>
    </html>
  );
}
